version: '3.8'

services:
  web:
    build: .
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - static_volume:/app/static
    env_file:
      - .env.prod
    depends_on:
      - db
    networks:
      - blog_network

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    networks:
      - blog_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - web
    networks:
      - blog_network

volumes:
  postgres_data:
  static_volume:

networks:
  blog_network:
    driver: bridge