# Generated by Django 5.2 on 2025-05-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the blog post', max_length=200)),
                ('content', models.TextField(help_text='The main content of the blog post')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the post was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the post was last updated')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
