# Generated by Django 5.2 on 2025-05-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(db_index=True, help_text='The title of the blog post', max_length=200),
        ),
    ]
