name: Django Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: blog
          POSTGRES_USER: blog_user
          POSTGRES_PASSWORD: blog_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create logs directory
        run: mkdir -p logs

      - name: Run Tests
        env:
          DEBUG: True
          SECRET_KEY: test-secret-key-123
          DB_NAME: blog
          DB_USER: blog_user
          DB_PASSWORD: blog_password
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          python manage.py test
